spring:
  application:
    name: platform

  # Conexión a la base de datos H2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # Consola web de H2
  h2:
    console:
      enabled: true

  # Configuración de JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    # MÁGICO: Espera a que se creen las tablas antes de ejecutar el import.sql
    defer-datasource-initialization: true

  # Inicialización de SQL
  sql:
    init:
      mode: always
